// Build-time service worker generation. The legacy web/sw.js kept a hand-
// maintained SHELL list in lockstep with ?v= query tags; here the bundle IS
// the manifest — the plugin bakes the hashed asset names into sw.js, so the
// shell list can never drift from what index.html actually loads.
//
// The runtime contract is copied from the legacy worker verbatim (it took
// several production incidents to get right — see DEPLOYMENT.md §5):
//   - cache-first everything; navigations serve the cached shell instantly
//     and revalidate in the background
//   - atomic install (addAll): a flaky glasses↔phone link can't leave a
//     half-populated cache
//   - activate deletes old caches only after the new one is populated
//   - navigations NEVER resolve empty — the glasses browser's own error page
//     is a dead end with no reload UI, so we serve a self-retrying page
//   - relay API paths are never intercepted

function swSource(cacheName, shell) {
  return `// GENERATED by web-next/sw-plugin.js — do not edit by hand.
const CACHE = ${JSON.stringify(cacheName)};
const SHELL = ${JSON.stringify(shell, null, 2)};

const RETRY_PAGE = \`<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="refresh" content="4">
<title>ambient link</title>
<style>body{background:#000;color:#eee;font:16px system-ui;display:flex;align-items:center;justify-content:center;height:100vh;margin:0}</style>
</head><body><div>reconnecting to relay…</div></body></html>\`;

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL)));
  self.skipWaiting();
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)))));
  self.clients.claim();
});
self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  if (/^\\/ambient-link\\/(ws|status|pair|sessions|ingest|hooks\\/|debug\\/|history)/.test(url.pathname)) return;
  if (e.request.method !== 'GET') return;

  if (e.request.mode === 'navigate') {
    e.respondWith(
      caches.match(e.request, { ignoreSearch: true })
        .then(r => r || caches.match('./index.html'))
        .then(hit => {
          const refresh = fetch(e.request).then(resp => {
            if (resp && resp.ok) {
              const copy = resp.clone();
              caches.open(CACHE).then(c => c.put(e.request, copy)).catch(() => {});
            }
            return resp;
          });
          if (hit) {
            e.waitUntil(refresh.catch(() => {}));
            return hit;
          }
          return refresh.catch(() =>
            new Response(RETRY_PAGE, { headers: { 'Content-Type': 'text/html' } })
          );
        })
    );
    return;
  }

  // Hashed assets: the content hash is the freshness key, so a cache hit is
  // always the right build and startup pays zero network round-trips.
  e.respondWith(
    caches.match(e.request).then(hit => {
      if (hit) return hit;
      return fetch(e.request).then(resp => {
        if (resp && resp.ok) {
          const copy = resp.clone();
          caches.open(CACHE).then(c => c.put(e.request, copy)).catch(() => {});
        }
        return resp;
      }).catch(() =>
        caches.match(e.request, { ignoreSearch: true }).then(r => r || Response.error())
      );
    })
  );
});
`;
}

export function generateServiceWorker() {
  return {
    name: 'ambient-link-sw',
    apply: 'build',
    generateBundle(_options, bundle) {
      const hashed = Object.keys(bundle)
        .filter((f) => f.startsWith('assets/'))
        .sort()
        .map((f) => './' + f);
      const shell = ['./', './index.html', ...hashed, './manifest.json', './icon.svg'];
      // Cache name derives from the hashed asset names: any content change
      // renames an asset, which changes sw.js bytes, which triggers the SW
      // update flow (install new cache → activate → controllerchange reload).
      let sig = 0;
      for (const ch of hashed.join('|')) sig = (sig * 31 + ch.charCodeAt(0)) >>> 0;
      const cacheName = 'ambient-link-svelte-' + sig.toString(36);
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: swSource(cacheName, shell) });
    },
  };
}
