// GENERATED by web-next/sw-plugin.js — do not edit by hand.
const CACHE = "ambient-link-svelte-a4ut01";
const SHELL = [
  "./",
  "./index.html",
  "./assets/index-D5dtZvO2.js",
  "./manifest.json",
  "./icon.svg"
];

const RETRY_PAGE = `<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="refresh" content="4">
<title>ambient link</title>
<style>body{background:#000;color:#eee;font:16px system-ui;display:flex;align-items:center;justify-content:center;height:100vh;margin:0}</style>
</head><body><div>reconnecting to relay…</div></body></html>`;

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL)));
  self.skipWaiting();
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)))));
  self.clients.claim();
});
self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  if (/^\/ambient-link\/(ws|status|pair|sessions|ingest|hooks\/|debug\/|history)/.test(url.pathname)) return;
  if (e.request.method !== 'GET') return;

  if (e.request.mode === 'navigate') {
    e.respondWith(
      caches.match(e.request, { ignoreSearch: true })
        .then(r => r || caches.match('./index.html'))
        .then(hit => {
          const refresh = fetch(e.request).then(resp => {
            if (resp && resp.ok) {
              const copy = resp.clone();
              caches.open(CACHE).then(c => c.put(e.request, copy)).catch(() => {});
            }
            return resp;
          });
          if (hit) {
            e.waitUntil(refresh.catch(() => {}));
            return hit;
          }
          return refresh.catch(() =>
            new Response(RETRY_PAGE, { headers: { 'Content-Type': 'text/html' } })
          );
        })
    );
    return;
  }

  // Hashed assets: the content hash is the freshness key, so a cache hit is
  // always the right build and startup pays zero network round-trips.
  e.respondWith(
    caches.match(e.request).then(hit => {
      if (hit) return hit;
      return fetch(e.request).then(resp => {
        if (resp && resp.ok) {
          const copy = resp.clone();
          caches.open(CACHE).then(c => c.put(e.request, copy)).catch(() => {});
        }
        return resp;
      }).catch(() =>
        caches.match(e.request, { ignoreSearch: true }).then(r => r || Response.error())
      );
    })
  );
});
